// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAydP1SZZa4XR4cGQPB5EUWDZ9RcBIM16U',
    appId: '1:870880784963:web:031309cf167bdef2945af6',
    messagingSenderId: '870880784963',
    projectId: 'clone-instagram-49869',
    authDomain: 'clone-instagram-49869.firebaseapp.com',
    storageBucket: 'clone-instagram-49869.appspot.com',
    measurementId: 'G-E5006GTK1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglk9XJHdmWEJQOPQwxdPcTnsheOb2wv4',
    appId: '1:870880784963:android:7ddfb3150838c8e2945af6',
    messagingSenderId: '870880784963',
    projectId: 'clone-instagram-49869',
    storageBucket: 'clone-instagram-49869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu3PtuvyQ1OZcgX00qHHRFSuyBxH8IegE',
    appId: '1:870880784963:ios:804d6b2ef504ff85945af6',
    messagingSenderId: '870880784963',
    projectId: 'clone-instagram-49869',
    storageBucket: 'clone-instagram-49869.appspot.com',
    iosClientId: '870880784963-0t16q34d9qfekrc4dkavur19rh3hvldp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneInstagram',
  );
}
